Vagrant.configure("2") do |config|
    config.vm.box = "precise64"
    config.vm.define :web do |web_config|
    	web_config.vm.hostname = "grunt.local"
        web_config.vm.network "private_network", ip: "192.168.50.11"
        web_config.vm.synced_folder "../../", "/vagrant/app"
        web_config.vm.provider "virtualbox" do |v|
		  v.memory = 512
		  v.cpus = 1
		end
        web_config.vm.provision "puppet" do |puppet|
            puppet.manifest_file = "vm-node.pp"
        end
    end
end